import type { SiteContent, Sermon } from "./types";
import seedSermons from "./seed-sermons.json";
import { SEED_TRANSLATIONS } from "./seed-translations";

// First-run content. Once the admin publishes, data/published.json takes over.

const yt = (id: string) => `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;

export const THEME_PRESETS = {
  "crimson-night": {
    label: "Crimson Night (brand)",
    colors: {
      bg: "#08070c",
      surface: "#14111b",
      text: "#f7f3ea",
      muted: "#a8a2b4",
      primary: "#c8102e",
      accent: "#e3b24f",
      glow: "#7b2cbf",
    },
  },
  "royal-light": {
    label: "Royal Light",
    colors: {
      bg: "#fbf8f2",
      surface: "#ffffff",
      text: "#1b1520",
      muted: "#6b6474",
      primary: "#b3122b",
      accent: "#a8781f",
      glow: "#d9a441",
    },
  },
  "midnight-gold": {
    label: "Midnight Gold",
    colors: {
      bg: "#050a16",
      surface: "#0e1628",
      text: "#f2efe6",
      muted: "#98a2b8",
      primary: "#d4a537",
      accent: "#f0cf7a",
      glow: "#1e4fd8",
    },
  },
} as const;

export function createSeed(): SiteContent {
  return {
    updatedAt: new Date().toISOString(),
    settings: {
      churchName: "Paralokanestham Ministries",
      shortName: "Paralokanestham",
      teluguName: "పరలోకనేస్తం",
      tagline: "Seek first the Kingdom of God",
      logo: "/brand/logo.png",
      emblem: "/brand/emblem.png",
      phone: "+91 99490 10301",
      email: "paralokanestham@gmail.com",
      whatsapp: "+91 99490 10301",
      address: "NKNR Gardens, Metro Pillar No. 846, Near Y-Junction, Habeeb Nagar, Moosapet, Kukatpally, Hyderabad, Telangana 500072",
      mapQuery: "Paralokanestham Ministries, NKNR Gardens, Moosapet, Hyderabad",
      serviceDay: "Every Sunday",
      serviceTimes: [
        { label: "1st Service", time: "6:00 AM" },
        { label: "2nd Service", time: "8:30 AM" },
        { label: "3rd Service", time: "11:00 AM" },
      ],
      socials: {
        youtube: "https://www.youtube.com/@ParalokanesthamMinistries",
        instagram: "https://www.instagram.com/paralokanesthamministries/",
        facebook: "https://www.facebook.com/Paralokanestham/",
        x: "https://x.com/PlnMinistries",
        whatsappChannel: "https://whatsapp.com/channel/0029VaFeWaM1noyzrsmYOB0L",
      },
      youtubeChannelId: "UCllVnL9Cbo1KFQu6MwBQhmA",
      giving: {
        // from the church's IDBI Bank UPI QR (decoded: pa, pn, mc)
        upiId: "m88nhd60pmh1@idbi",
        payeeName: "Pattapu Isaac",
        qrImage: "/brand/upi-qr.jpg",
        merchantCode: "5999",
        note: "After giving, send us a WhatsApp message with your name and purpose so we can pray over your offering and send a receipt.",
      },
      connectForms: [
        {
          id: "prayer",
          title: "Prayer Request",
          text: "Whatever you are facing, you don't have to face it alone. Share your need and our pastors and prayer team will stand with you in faith.",
          icon: "HandHeart",
          buttonLabel: "Send prayer request",
          askMessage: true,
          messageLabel: "How can we pray for you?",
          extraFields: [],
          whatsappIntro: "🙏 Prayer Request",
        },
        {
          id: "baptism",
          title: "Get Baptised",
          text: "Ready to take your next step with Jesus? Baptism is a public declaration of your faith. Sign up and we'll walk you through it.",
          icon: "Droplets",
          buttonLabel: "Sign up for baptism",
          askMessage: false,
          extraFields: ["Area / Locality"],
          whatsappIntro: "💧 Baptism Sign-up",
        },
        {
          id: "volunteer",
          title: "Join as a Volunteer",
          text: "Use your gifts to serve God's house in worship, media, hospitality, parking, children's ministry and more. There's a place for you on the team.",
          icon: "Users",
          buttonLabel: "Join the team",
          askMessage: true,
          messageLabel: "Where would you love to serve?",
          extraFields: [],
          whatsappIntro: "🙌 Volunteer Sign-up",
        },
      ],
      announcement: {
        enabled: true,
        text: "Christmas and New Year's Eve services: save the dates! Timings will be announced soon.",
        href: "/events",
      },
      footerBlurb:
        "A Spirit-filled church family in Hyderabad, gathering every Sunday to worship, hear God's Word and experience His healing presence.",
    },
    theme: {
      preset: "crimson-night",
      colors: { ...THEME_PRESETS["crimson-night"].colors },
      displayFont: "cinzel",
      bodyFont: "manrope",
      radius: 18,
      uppercaseHeadings: true,
    },
    sermonCategories: [
      { id: "prophetic-sunday", name: "Prophetic Sunday", description: "Prophetic worship, Word and healing prayers." },
      { id: "holy-communion", name: "Holy Communion Sunday", description: "First Sunday of every month around the Lord's table." },
      { id: "special-services", name: "Special Services", description: "Christmas, New Year, Good Friday, Easter and anniversaries." },
      { id: "anointing", name: "Olive Oil Anointing", description: "Olive Oil Anointing Festival services." },
      { id: "short-sermons", name: "20-Minute Sermons", description: "Short, powerful messages for everyday life." },
      { id: "teaching", name: "Teachings", description: "Messages and conference teachings by Dr. P. Isaac." },
      { id: "daily-word", name: "Daily Word of God", description: "Daily prophetic prayer and a word for the day." },
      { id: "testimonies", name: "Testimonies", description: "Stories of God's faithfulness in our church family." },
      { id: "short-messages", name: "Short Messages", description: "Quick encouragement for your week." },
      { id: "sunday-service", name: "Sunday Service", description: "Full Sunday services." },
    ],
    speakers: ["Dr. P. Isaac", "Bro. Prashanth"],
    sermons: (seedSermons as Sermon[]).map((s, i) => ({ ...s, featured: i === 0 })),
    translations: structuredClone(SEED_TRANSLATIONS),
    events: [
      {
        id: "christmas-2026",
        title: "Christmas Celebrations",
        subtitle: "Celebrate the birth of our Saviour",
        startDate: "2026-12-25",
        time: "Timings will be updated soon",
        location: "NKNR Gardens, Kukatpally",
        description:
          "Join the whole Paralokanestham family for a joyful Christmas celebration with worship, carols, a special Christmas message from Dr. P. Isaac and prayers for every family. Bring your friends and neighbours!",
        tag: "Christmas",
        featured: true,
        ctaLabel: "Watch last year's celebration",
        ctaHref: "/sermons?watch=8Homi6AfjNk",
      },
      {
        id: "watch-night-2026",
        title: "New Year's Eve Watch Night Service",
        subtitle: "Step into 2027 in God's presence",
        startDate: "2026-12-31",
        time: "Timings will be updated soon",
        location: "NKNR Gardens, Kukatpally",
        description:
          "Close the year with thanksgiving and enter the new year in prayer. A night of worship, prophetic words and blessing as we cross over into 2027 together.",
        tag: "New Year",
        featured: true,
        ctaLabel: "Watch last year's highlights",
        ctaHref: "/sermons?watch=bVbHgrnFOzE",
      },
    ],
    pages: [
      {
        id: "home",
        slug: "",
        title: "Home",
        showInNav: false,
        hidden: false,
        seoTitle: "Paralokanestham Ministries | Church in Hyderabad",
        seoDescription:
          "Paralokanestham Ministries is a Spirit-filled church in Kukatpally, Hyderabad led by Dr. P. Isaac. Sunday services at 6:00, 8:30 & 11:00 AM at NKNR Gardens. Watch live online.",
        sections: [
          {
            id: "s-welcome",
            type: "welcome",
            props: {
              slides: [
                {
                  title: "Welcome to Paralokanestham Ministries",
                  subtitle: "Seek first the Kingdom of God. A church family in Hyderabad where you can encounter His presence, His Word and His healing power.",
                  background: "gradient",
                  image: "",
                  youtubeId: "",
                  primary: { label: "Get connected", href: "/connect" },
                  secondary: { label: "Learn more", href: "/about" },
                },
                {
                  title: "Seek First The Kingdom",
                  subtitle: "Join us this Sunday in person at NKNR Gardens, Kukatpally, or live online.",
                  background: "photo",
                  image: "/images/ig/ig2.jpg",
                  youtubeId: "",
                  primary: { label: "Plan your visit", href: "/visit" },
                  secondary: { label: "Watch live", href: "/sermons#live" },
                },
              ],
              autoplay: true,
              interval: 7,
              height: "large",
              showServiceTimes: true,
            },
          },
          {
            id: "s-latest",
            type: "latestSermon",
            props: { eyebrow: "Latest message", title: "Watch this week's service", mode: "latest", videoId: "", ctaLabel: "All messages" },
          },
          {
            id: "s-experience",
            type: "cardGrid",
            props: {
              eyebrow: "Find your place",
              title: "Join us in person or online",
              subtitle: "However you connect, there's a seat saved for you.",
              style: "image",
              columns: 4,
              items: [
                { title: "In Person", text: "Three services every Sunday at NKNR Gardens, Kukatpally.", image: "/images/ig/ig2.jpg", href: "/visit", cta: "Plan a visit" },
                { title: "Watch Live", text: "Every service streams live on YouTube for our online family.", image: "/images/ig/ig4.jpg", href: "/sermons#live", cta: "Watch now" },
                { title: "Daily Word", text: "Start each day with a prophetic prayer and a word from God.", image: "/images/ig/ig6.jpg", href: "/sermons?category=daily-word", cta: "Today's word" },
                { title: "Get Connected", text: "Prayer, baptism and serving. Take your next step.", image: "/images/ig/ig9.jpg", href: "/connect", cta: "Next steps" },
              ],
            },
          },
          {
            id: "s-gatherings",
            type: "cardGrid",
            props: {
              eyebrow: "Our gatherings",
              title: "Where heaven meets earth",
              subtitle: "Every Sunday is an encounter. Some Sundays are set apart.",
              style: "icon",
              columns: 4,
              items: [
                { title: "Prophetic Sunday", text: "Prophetic worship, the Word and healing prayers for every family.", icon: "Flame", href: "/sermons?category=prophetic-sunday", cta: "Watch" },
                { title: "Holy Communion Sunday", text: "The first Sunday of every month we gather around the Lord's table.", icon: "Wine", href: "/sermons?category=holy-communion", cta: "Watch" },
                { title: "Olive Oil Anointing", text: "A festival of anointing, breakthrough and blessing over your life.", icon: "Droplet", href: "/sermons?category=anointing", cta: "Watch" },
                { title: "Daily Word of God", text: "Prophetic prayer by Dr. P. Isaac, published every day online.", icon: "BookOpen", href: "/sermons?category=daily-word", cta: "Listen" },
              ],
            },
          },
          {
            id: "s-stats",
            type: "stats",
            props: {
              items: [
                { value: "13", label: "Years of grace" },
                { value: "3", label: "Services every Sunday" },
                { value: "38K+", label: "Online family" },
                { value: "4,200+", label: "Messages online" },
              ],
            },
          },
          {
            id: "s-events",
            type: "eventsList",
            props: { eyebrow: "Coming up", title: "Upcoming events", subtitle: "", limit: 3, layout: "cards", ctaLabel: "See all events" },
          },
          {
            id: "s-leaders",
            type: "leaders",
            props: {
              eyebrow: "Our pastors",
              title: "Led with a shepherd's heart",
              items: [
                { name: "Dr. P. Isaac", role: "Founder & Senior Pastor", image: "/brand/pastor-isaac.jpg", bio: "Founder of Paralokanestham Ministries, Dr. P. Isaac has shepherded this church family for over 13 years with a passion for God's Word, prophetic prayer and healing." },
                { name: "Bro. Prashanth Pattapu", role: "Pastor", image: "/images/ig/ig4.jpg", bio: "Bro. Prashanth leads alongside Dr. Isaac, ministering the Word with fresh fire and a heart for the next generation." },
              ],
            },
          },
          {
            id: "s-testimonies",
            type: "videoGrid",
            props: { eyebrow: "Testimonies", title: "Stories of God's faithfulness", category: "testimonies", limit: 4 },
          },
          {
            id: "s-connect-cta",
            type: "ctaBanner",
            props: {
              title: "We'd love to pray with you",
              text: "Send a prayer request, sign up for baptism or join the volunteer team. It only takes a minute on WhatsApp.",
              primary: { label: "Send a prayer request", href: "#form:prayer" },
              secondary: { label: "All next steps", href: "/connect" },
              tone: "primary",
            },
          },
          {
            id: "s-visit",
            type: "visit",
            props: { eyebrow: "Visit us", title: "Your seat is saved", text: "Arrive a few minutes early and our team will welcome you, help you find a seat and answer any questions.", showMap: true },
          },
        ],
      },
      {
        id: "sermons",
        slug: "sermons",
        title: "Sermons",
        navLabel: "Sermons",
        showInNav: true,
        hidden: false,
        seoDescription: "Watch sermons, Sunday services, Daily Word of God and testimonies from Paralokanestham Ministries.",
        sections: [
          { id: "s-sermons-head", type: "pageHeader", props: { eyebrow: "Messages", title: "Sermons", subtitle: "Sunday services, prophetic prayer and teaching from Dr. P. Isaac and the Paralokanestham pulpit. Watch them right here.", image: yt("oD-syb78Jk4"), size: "medium" } },
          { id: "s-library", type: "sermonLibrary", props: { showLive: true, liveTitle: "Watch live", liveText: "Services stream live every Sunday at 6:00, 8:30 and 11:00 AM IST." } },
        ],
      },
      {
        id: "events",
        slug: "events",
        title: "Events",
        navLabel: "Events",
        showInNav: true,
        hidden: false,
        seoDescription: "Upcoming events at Paralokanestham Ministries: Christmas celebrations and the New Year's Eve Watch Night service.",
        sections: [
          { id: "s-events-head", type: "pageHeader", props: { eyebrow: "What's happening", title: "Events", subtitle: "Special services and gatherings for the whole family. Timings for upcoming events will be updated soon.", image: "", size: "medium" } },
          { id: "s-events-all", type: "eventsList", props: { eyebrow: "", title: "", subtitle: "", limit: 20, layout: "list", ctaLabel: "" } },
          {
            id: "s-events-cta",
            type: "ctaBanner",
            props: { title: "Can't make it in person?", text: "Every special service streams live on our YouTube channel.", primary: { label: "Watch live", href: "/sermons#live" }, secondary: { label: "Subscribe on YouTube", href: "https://www.youtube.com/@ParalokanesthamMinistries?sub_confirmation=1" }, tone: "dark" },
          },
        ],
      },
      {
        id: "give",
        slug: "give",
        title: "Give",
        navLabel: "Give",
        showInNav: true,
        hidden: false,
        seoDescription: "Give to Paralokanestham Ministries with UPI: PhonePe, Google Pay, Paytm or QR code.",
        sections: [
          { id: "s-give-head", type: "pageHeader", props: { eyebrow: "Generosity", title: "Give", subtitle: "Your generosity helps us spread the Gospel, care for families and reach Hyderabad and beyond.", image: "", size: "medium" } },
          { id: "s-giving", type: "giving", props: { title: "Give with UPI", subtitle: "Tap PhonePe, Google Pay or Paytm on your phone, or scan the QR code with any UPI app." } },
          { id: "s-give-verse", type: "verse", props: { text: "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.", reference: "2 Corinthians 9:7" } },
        ],
      },
      {
        id: "connect",
        slug: "connect",
        title: "Get Connected",
        navLabel: "Get Connected",
        showInNav: true,
        hidden: false,
        seoDescription: "Send a prayer request, sign up for baptism or join the volunteer team at Paralokanestham Ministries.",
        sections: [
          { id: "s-connect-head", type: "pageHeader", props: { eyebrow: "Next steps", title: "Get Connected", subtitle: "Church is better together. Choose a next step below and we'll continue the conversation on WhatsApp.", image: "/images/ig/ig10.jpg", size: "medium" } },
          { id: "s-connect", type: "connectOptions", props: { eyebrow: "", title: "How can we help you?", subtitle: "" } },
          { id: "s-connect-verse", type: "verse", props: { text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", reference: "Matthew 6:33" } },
        ],
      },
      {
        id: "about",
        slug: "about",
        title: "About",
        navLabel: "About",
        showInNav: true,
        hidden: false,
        seoDescription: "About Paralokanestham Ministries: our story, our pastors and what we believe.",
        sections: [
          { id: "s-about-head", type: "pageHeader", props: { eyebrow: "Who we are", title: "About Us", subtitle: "", image: "/images/ig/ig3.jpg", size: "medium" } },
          {
            id: "s-story",
            type: "splitFeature",
            props: {
              eyebrow: "Our story",
              title: "13 years of grace & faithfulness",
              text: "For more than 13 years, Paralokanestham Ministries, part of the Laymen's Gospel Fellowship, has been a growing church family, gathering every Sunday at NKNR Gardens in Kukatpally and online around the world.\n\nUnder the leadership of our founder Dr. P. Isaac, Paralokanestham is a place of prophetic worship, sound teaching from God's Word, healing and deliverance, where families are restored and lives are transformed.",
              image: "/images/ig/ig2.jpg",
              imagePosition: "right",
              cta: { label: "Plan your visit", href: "/visit" },
            },
          },
          { id: "s-about-stats", type: "stats", props: { items: [{ value: "2013", label: "Founded" }, { value: "3", label: "Sunday services" }, { value: "38K+", label: "Online family" }, { value: "4,200+", label: "Messages online" }] } },
          {
            id: "s-about-leaders",
            type: "leaders",
            props: {
              eyebrow: "Leadership",
              title: "Our pastors",
              items: [
                { name: "Dr. P. Isaac", role: "Founder & Senior Pastor", image: "/brand/pastor-isaac.jpg", bio: "Founder of Paralokanestham Ministries, Dr. P. Isaac has shepherded this church family for over 13 years with a passion for God's Word, prophetic prayer and healing." },
                { name: "Bro. Prashanth Pattapu", role: "Pastor", image: "/images/ig/ig4.jpg", bio: "Bro. Prashanth leads alongside Dr. Isaac, ministering the Word with fresh fire and a heart for the next generation." },
              ],
            },
          },
          {
            id: "s-values",
            type: "cardGrid",
            props: {
              eyebrow: "What we value",
              title: "What we're about",
              subtitle: "",
              style: "icon",
              columns: 3,
              items: [
                { title: "The Word", text: "We build our lives on the truth of Scripture, preached with clarity and power.", icon: "BookOpen", href: "", cta: "" },
                { title: "His Presence", text: "We make room for the Holy Spirit in worship, prophecy and prayer.", icon: "Flame", href: "", cta: "" },
                { title: "Healing & Family", text: "We believe God heals, restores and blesses families, and we pray for it.", icon: "Heart", href: "", cta: "" },
              ],
            },
          },
          { id: "s-about-verse", type: "verse", props: { text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", reference: "Matthew 6:33" } },
        ],
      },
      {
        id: "visit",
        slug: "visit",
        title: "Plan a Visit",
        navLabel: "Visit",
        showInNav: true,
        hidden: false,
        seoDescription: "Plan your visit to Paralokanestham Ministries: Sunday service times, directions and what to expect.",
        sections: [
          { id: "s-visit-head", type: "pageHeader", props: { eyebrow: "I'm new", title: "Plan Your Visit", subtitle: "We can't wait to meet you. Here's everything you need for your first Sunday.", image: "/images/ig/ig10.jpg", size: "medium" } },
          { id: "s-visit-times", type: "serviceTimes", props: { title: "Sunday service times", subtitle: "Choose the service that works best for your family." } },
          {
            id: "s-expect",
            type: "cardGrid",
            props: {
              eyebrow: "What to expect",
              title: "Your first Sunday",
              subtitle: "",
              style: "icon",
              columns: 4,
              items: [
                { title: "A warm welcome", text: "Our hospitality team will greet you at the entrance and help you find a seat.", icon: "Smile", href: "", cta: "" },
                { title: "Spirited worship", text: "Telugu worship that lifts your heart and brings you into God's presence.", icon: "Music", href: "", cta: "" },
                { title: "A life-giving word", text: "A Bible message you can carry into your week, with prayer for every need.", icon: "BookOpen", href: "", cta: "" },
                { title: "Easy parking", text: "Ample parking at NKNR Gardens, right on the Kukatpally metro line.", icon: "Car", href: "", cta: "" },
              ],
            },
          },
          { id: "s-visit-map", type: "visit", props: { eyebrow: "Location", title: "Find us", text: "We're at NKNR Gardens near Metro Pillar No. 846, close to Y-Junction, Kukatpally.", showMap: true } },
        ],
      },
      {
        id: "sunday-school",
        slug: "sunday-school",
        title: "Sunday School",
        navLabel: "Sunday School",
        showInNav: true,
        hidden: true,
        seoDescription: "Sunday School for children at Paralokanestham Ministries.",
        sections: [
          { id: "s-ss-head", type: "pageHeader", props: { eyebrow: "Kids", title: "Sunday School", subtitle: "Helping children know, love and follow Jesus.", image: "", size: "medium" } },
          { id: "s-ss-soon", type: "comingSoon", props: { title: "Coming soon", text: "Details about Sunday School classes, age groups and timings will be shared here soon.", icon: "Baby" } },
        ],
      },
    ],
  };
}
